---
title: "index"
output: html_document
date: "2022-09-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(igraph)
library(ggraph)
library(tidygraph)
library(writexl)
library(RColorBrewer)
library(reshape)
library(maditr)
library(patchwork)
library(jtools)
```

```{r}
read_csv("data/SP2021_C1_workshop_1_edges_w_topics.csv") -> edges
select(edges, 1,4) -> edges
read_csv("data/SP2021_C1_workshop_1_nodes_w_topics_C.P.csv") -> nodes
net <- graph_from_data_frame(d = edges, vertices = nodes, directed = FALSE) 
```

```{r}
#2-mode network (shown in methods slide for NCTM 2022 presentation)
net -> net1
bipartite_mapping(net1) # test to see if bipartite
V(net1)$type <- bipartite_mapping(net1)$type #distinguishes the nodes by mode
V(net1)$color <- ifelse(V(net1)$type, "lightblue", "salmon")
V(net1)$shape <- ifelse(V(net1)$type, "circle", "square")
E(net1)$color <- "lightgray"
plot(net1)
plot(net1, vertex.label.cex = 0.5, vertex.label.color = "black")
```

```{r}
#Table 1: Participant-Potential Norm Association
E(net)$weight <- 1
net <- simplify(net, edge.attr.comb=list(weight="sum"))
as_data_frame(net, what = c("edges")) -> net_edges
slice(nodes, 17:51) -> nodes1
select(nodes1, 1,4) -> nodes1
colnames(nodes1) <- c("to","topic_name")
left_join(net_edges, nodes1, by = "to") -> topic_degree
select(topic_degree, 1,3,4) -> topic_degree
result = dcast(topic_degree, from ~ topic_name, value.var="weight", fun.aggregate=sum) -> topic_degree.1
colnames(result)[1] <- c("Participant")
```

```{r}
#Figure 1: Participant-Potential Norm 2-Mode Network
set.seed(123)
net2 <- create_layout(net, layout = "fr")
p1 <- ggraph(net2) +
  geom_edge_link(alpha=.75) +
  geom_node_point(aes(color = `Node Type`, shape = Mode), size = 10) +
  scale_color_manual(values = c("slateblue1", "green4", "darkblue", "red", "steelblue1", "thistle2")) +
  geom_node_text(aes(label= name), color = "white", size = 4) +
  scale_shape_manual(values = c("circle", "square")) +
  scale_fill_discrete(breaks = c("Core", "Periphery","Feedback", "Attending to student thinking", "Annotating student thinking", "Sorting student work")) +
  theme_graph()

#Figure 2: Participant-Feedback 2-Mode Network
fback.net <- slice(net2, 1:31)
p2 <- ggraph(fback.net) +
  geom_edge_link(aes(width = weight), alpha = .35) +
  geom_node_point(aes(color = `Node Type`, shape = Mode), size = 10) +
  scale_color_manual(values = c("darkblue", "red", "steelblue1")) +
  geom_node_text(aes(label= name), color = "white", size = 4) +
  scale_shape_manual(values = c("circle", "square")) +
  theme_graph()
```

```{r}
#Attending to student thinking plot (not in presentation)
AtST <- select(nodes, 1)
AtST <- slice(AtST, 1:16,32:38)
as_vector(AtST) -> AtST
AtST.net <- induced_subgraph(net1, AtST)
AtST.net.lay <- create_layout(AtST.net, layout = "kk")

p3 <- ggraph(AtST.net.lay) +
  geom_edge_link(alpha = .35) +
  geom_node_point(aes(color = `Node Type`, shape = Mode), size = 10) + 
  scale_color_manual(values = c("green4", "darkblue", "steelblue1")) +
  geom_node_text(aes(label= name), color = "white", size = 4) +
  scale_shape_manual(values = c("circle", "square")) +
  theme_graph()

#Annotating to student thinking plot (not in presentation)
AnST <- select(nodes, 1)
AnST <- slice(AnST, 1:16,39:42)
as_vector(AnST) -> AnST
AnST.net <- induced_subgraph(net1, AnST)
AnST.net.lay <- create_layout(AnST.net, layout = "kk")

p4 <- ggraph(AnST.net.lay) +
  geom_edge_link(alpha = .35) +
  geom_node_point(aes(color = `Node Type`, shape = Mode), size = 10) + 
  scale_color_manual(values = c("slateblue1", "darkblue", "steelblue1")) +
  geom_node_text(aes(label= name), color = "white", size = 4) +
  scale_shape_manual(values = c("circle", "square")) +
  theme_graph()

#Sorting student work plot (not in presentation)
SoSW <- select(nodes, 1)
SoSW <- slice(SoSW, 1:16,43:51)
as_vector(SoSW) -> SoSW
SoSW.net <- induced_subgraph(net1, SoSW)
SoSW.net.lay <- create_layout(SoSW.net, layout = "fr")

p5 <- ggraph(SoSW.net.lay) +
  geom_edge_link(alpha = .35) +
  geom_node_point(aes(color = `Node Type`, shape = Mode), size = 10) + 
  scale_color_manual(values = c("darkblue", "steelblue1","thistle2")) +
  geom_node_text(aes(label= name), color = "white", size = 4) +
  scale_shape_manual(values = c("circle", "square")) +
  theme_graph()

```

```{r}
#Projects 2-mode participant-discourse feature network to 1-mode participant co-use of discourse features network
V(net)$type <- bipartite_mapping(net)$type #distinguishes the nodes by mode
Part_association <- as_incidence_matrix(net) %*% t(as_incidence_matrix(net)) 
diag(Part_association) <- 0
Part_association[lower.tri(Part_association)] <- 0
net2 <-graph_from_adjacency_matrix(Part_association) 
EL <- get.edgelist(net2)
EL1 <- as_tibble(EL)
nodes.bp <- slice(nodes, 1:16)
net3 <- graph_from_data_frame(d = EL1, vertices = nodes.bp, directed = FALSE)
E(net3)$weight <- 1 #assign weight of one to each edge
net4<-simplify(net3, edge.attr.comb=list(weight="sum")) #collapse multiple edges into weighted according to sum

#Figure 3: Participant co-use of discourse features network
set.seed(456)
projection <- create_layout(net4, layout = "fr")
p6 <- ggraph(projection) +
  geom_edge_link(aes(width = weight), alpha = .35)+
  geom_node_point(aes(color = `Node Type`), size = 10) +
  scale_color_manual(values = c("darkblue","steelblue1")) +
  geom_node_text(aes(label= name), color = "white", size = 4) +
  theme_graph()
```

```{r}
#Table 2: Participant Co-use of Discourse Feature Network Statistics
Network_stats <- data_frame(
  id = V(net4)$name,
  Degree = degree(net4),
  Betweenness = betweenness(net4, normalized = TRUE),
  Closeness = closeness(net4),
  Eigenvector = eigen_centrality(net4, directed=F, weights=E(net4)$weights)$vector
  )
```

Below was not shown in NCTM 2022 presentation
```{r}
#cohesiveness of 1-mode graph
Cohesiveness <- function(gr){ 
  Den = edge_density(gr)
  Recip = reciprocity(gr)
  Eff = brainGraph::efficiency(gr, type = "global")
  Diam = diameter(gr)
  Trans = transitivity(gr)
  Cent = centralization.degree(gr, mode = "all")$centralization
  df = tibble(Den, Recip, Eff, Diam, Trans, Cent)
  return(df)  
}
as_tibble(Cohesiveness(net2)) -> newdf
```

```{r}
#linear models for individual centrality from 1 mode project and core/intermediate/periphery position
left_join(Network_stats, nodes, by ="id") -> Network_stats
select(Network_stats, 1:5,8) -> Network_stats
lm_model.deg <- lm(Degree ~ `Node Type`, data = Network_stats)
lm_model.bet <- lm(Betweenness ~ `Node Type`, data = Network_stats)
lm_model.clo <- lm(Closeness ~ `Node Type`, data = Network_stats)
lm_model.eig <- lm(Eigenvector ~ `Node Type`, data = Network_stats)
model_results <- export_summs(lm_model.deg, lm_model.bet, lm_model.clo, lm_model.eig, error_format = "[{conf.low}, {conf.high}]", model.names = c("Degree", "Betweenness", "Closeness", "Eigenvector")) 
```

```{r}

```

